# Generated by OOP Practice Lab maintenance.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="exercises_completed",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by", to="exercises.exercise"
            ),
        ),
    ]
